### PR TITLE
Fix escaping named parameters

### LINKED ISSUE #30: Query errors out with JSONB operators
A couple of JSONB operators like `?|` and `?&` don't play nice with the library.
Notice how they seem to be interpreted as named parameters in the first query.

```haskell
-- @?|@ is probably being interpreted as a named parameter
> extractNames "SELECT foo FROM my_table WHERE (foo->'mood'->'tag_keys' ?| ?selectedTags);"
Left PostgreSQL named parameter error: Query contains an empty name: SELECT  foo FROM my_table WHERE (foo->'mood'->'tag_keys' ?| ?selectedTags);
>
-- @> works perfectly fine.Not that this query itself is correct. 
-- Just using it to enable some contrast with the above
> extractNames "SELECT foo FROM my_table WHERE (foo->'mood'->'tag_keys' @> ?selectedTags);"
Right ("SELECT foo FROM my_table WHERE (foo->'mood'->'tag_keys' @> ?);","selectedTags" :| [])
```

### PR DESCRIPTION
**Pull request by nitinprakash96**
Fixes #30 

`postgres-simple` uses an extra `?` at the front of any operator to make sure that it is escaped. Using the same logic, we make sure that by having an extra `?` at the front of an operator, it doesn't get parsed as a named parameter. 

```haskell
-- operator is escaped using double question marks
> extractNames "SELECT foo FROM my_table WHERE (foo->'bar' ??| ?selectedTags);"
Right ("SELECT foo FROM my_table WHERE (foo->'bar' ?| ?);","selectedTags" :| [])

-- Gets interpreted as a named param if not escaped
> extractNames "SELECT foo FROM my_table WHERE (foo->'bar' ?| ?selectedTags);"
Left PostgreSQL named parameter error: Query contains an empty name: SELECT foo FROM my_table WHERE (foo->'bar' ?| ?selectedTags);
```

### CODE REVIEW

**Comment by nitinprakash96** [comment]
~Converted to draft to test this a bit more. (will do over the weekend)~

**Review by jhrcek — CHANGES_REQUESTED** [review]
It's great that you found a solution based on already used helper function from postgres-simple!

But could you please add a test for this as well?
Just a positive test for this (basically just copy paste the haddock examples into the Spec.hs)?

Also I think we should migrate the CI config to github actions similar to what we did in other repos.
It shouldn't be much more than almost copy paste..

**Comment by jhrcek** [comment]
Update on my previous comment: since we run doctest tests in CI, there's no need to duplicate those tests in Spec.hs.

But I'd still kindly ask you to migrate this repo to github actions so the CI actually runs.

**Comment by turboMaCk** [comment]
I think gh actions migrations should be done in separate PR.

**Comment by jhrcek** [comment]
@turboMaCk ok, let me do the GH actions migration first before we merge this.
PR coming today..

**Review by turboMaCk — APPROVED** [review]
LGTM

**Review by jhrcek — APPROVED** [review]
Thanks, looks good.
And I verified the 2 new doctests were executed in CI.

**Pull request merged**
