### PR TITLE
Add support for GHC 9.0.2 (LTS 19.0)

### PR DESCRIPTION
**Pull request by michivi**

### CODE REVIEW

**Comment by nitinprakash96** [comment]
Thanks a lot for doing this @michivi ! Also, I think it'd be fine if we remove v8.6.5 from CI. I saw the number of downloads on hackage and its pretty low (seems as if we're the only users and we're all using >= v8.8.4, I think). Not that it's a necessity. What do you think? cc: @jhrcek @turboMaCk

**Comment by jhrcek** [comment]
Yes, please let's remove 8.6.5.
- supporting only the latest 3 major ghc versions sounds more than sufficient to me
- it will save CI resources and lower the maintenance burden for us
- we should encourage haskell community to migrate to more recent versions of GHC
- judging by the number of downloads of this library on hackage I'd say that we at holmusk might be the only users of it :smile: 
- even if anyone is using an older GHC they can still use the latest released version of the library
- based on latest State of Haskell survey most people have migrated to 8.10 anyway (https://taylor.fausak.me/2021/11/16/haskell-survey-results/#s2q4)

**Comment by turboMaCk** [comment]
downloads are kind of awkward metric. Even we don't bump these by using the library because it's cached everywhere (your machine, my machine, ci....)

**Comment by michivi** [comment]
Yes, I see your point. Done! (with a little pinch of sadness 😅)

**Review by turboMaCk — APPROVED** [review]

**Comment by jhrcek** [comment]
> with a little pinch of sadness

Can I inquire what's causing the sadness? :smile_cat: 
Is it that we're not trying to keep as much backward compatibility as possible?

**Review by jhrcek — APPROVED** [review]
LGTM

**Comment by michivi** [comment]
No, it's just that I have fund memories with GHC 8.6.5... so absolutely no real objective reasons related to this PR... or Haskell in general 😁

**Pull request merged**
